### PR TITLE
add gallery section

### PR DESCRIPTION
**Pull request by Sabrina0668**
### how : use scss

image

### CODE REVIEW

**Review by tatoMa — COMMENTED** [review]
Please pay attention to fonts and icons.

image

**Comment by Kaifeng-Sun** [comment]
> Please pay attention to fonts and icons.
> 
> image

Resolved. The font size was using the vw to change size based on the screen width so may little different from the design.

**Review by tatoMa — COMMENTED** [review]
The gaps between icon and text.

image

**Review by tatoMa — APPROVED** [review]
LGTM

**Pull request merged**
