### PR TITLE
feat: add sponsor section into project

### PR DESCRIPTION
**Pull request by HjsCS**

### CODE REVIEW

**Comment by tatoMa** [comment]
Seems not finished yet?

**Comment by HjsCS** [comment]
forgot to import component in page index😅😅😅

**Review by tatoMa — COMMENTED** [review]
Please pay attention to the colors.

image

**Comment by HjsCS** [comment]
it is white text, when I run the dev on my machine.

**Review by tatoMa — APPROVED** [review]
LGTM

**Pull request merged**
